# Generated by Django 5.2.6 on 2025-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amount_left',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
